/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class service_TradingServiceJNI */

#ifndef _Included_service_TradingServiceJNI
#define _Included_service_TradingServiceJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef service_TradingServiceJNI_BUY
#define service_TradingServiceJNI_BUY 0L
#undef service_TradingServiceJNI_SELL
#define service_TradingServiceJNI_SELL 1L
#undef service_TradingServiceJNI_MARKET
#define service_TradingServiceJNI_MARKET 0L
#undef service_TradingServiceJNI_LIMIT
#define service_TradingServiceJNI_LIMIT 1L
/*
 * Class:     service_TradingServiceJNI
 * Method:    getCashBalance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_service_TradingServiceJNI_getCashBalance
  (JNIEnv *, jobject);

/*
 * Class:     service_TradingServiceJNI
 * Method:    getOpenPositions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_service_TradingServiceJNI_getOpenPositions
  (JNIEnv *, jobject);

/*
 * Class:     service_TradingServiceJNI
 * Method:    placeOrder
 * Signature: (Ljava/lang/String;IIID)V
 */
JNIEXPORT void JNICALL Java_service_TradingServiceJNI_placeOrder
  (JNIEnv *, jobject, jstring, jint, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
